### ISSUE TITLE
Panic when joysticks are attached

### ISSUE THREAD

**Issue by MrMinimal** [Jonesey13/multiinput-rust#3]
Thanks for this library, great to see xinput isn't the only option!
I am currently evaluating if it can be used for controller input for the amethyst game engine.

I ran into a panic when trying out the apitest example with a Thrustmaster Warthog joystick.

This line panics because of the assert, if the assert is removed the joystick works just fine.
https://github.com/Jonesey13/multiinput-rust/blob/master/src/joystick.rs#L74

I edited `joystick.rs` for a bit more information before the panic occurs:
https://gist.github.com/MrMinimal/cadc02b575ed7f8d5c0e1389f9d23dc1

# Log
```
PS C:\Users\Dev\Documents\RustProjects\multiinput-rust> cargo run --example apitest
    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
     Running `target\debug\examples\apitest.exe`
Mice:
["\\\\?\\HID#VID_093A&PID_2521#6&2c46c546&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}\u{0}"]None
["\\\\?\\HID#VID_04D9&PID_0141&MI_02&Col03#7&2b29a21e&0&0002#{378de44c-56ef-11d1-bc8c-00a0c91405dd}\u{0}"]
None
Keyboards:
["\\\\?\\HID#VID_04D9&PID_0141&MI_02&Col04#7&2b29a21e&0&0003#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}\u{0}"]
None
["\\\\?\\HID#VID_04D9&PID_0141&MI_00#7&15f24e50&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}\u{0}"]
None
Hids:
["\\\\?\\HID#VID_044F&PID_0404#6&1345e89e&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\u{0}"]None
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: 1114112
Should be: 1114112
HidP_GetUsageValue returns: -1072627702
Should be: 1114112
thread '<unnamed>' panicked at 'assertion failed: HidP_GetUsageValue(HidP_Input, value_caps.UsagePage, 0, usage_index,
                   &mut value,
                   hid_info.preparsed_data.as_mut_ptr() as
                       PHIDP_PREPARSED_DATA,
                   transmute::<_, PCHAR>(raw_data.bRawData.as_ptr()),
                   raw_data.dwSizeHid) == HIDP_STATUS_SUCCESS', src\joystick.rs:77:6
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', libcore\result.rs:945:5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', libcore\result.rs:945:5
stack backtrace:
   0:     0x7ff7cd9aa59a - std::sys::windows::backtrace::unwind_backtrace
                               at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1:     0x7ff7cd9b0dff - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2:     0x7ff7cd9b0dff - std::sys_common::backtrace::print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff7cd9a5a2e - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:207
   4:     0x7ff7cd9a56da - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:223
   5:     0x7ff7cd9a5fee - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:402
   6:     0x7ff7cd9a5d9f - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:349
   7:     0x7ff7cd9a5cc1 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:325
   8:     0x7ff7cd9b657c - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:72
   9:     0x7ff7cd9394c2 - core::result::unwrap_failed<std::sync::mpsc::SendError<multiinput::manager::Command>>
                               at C:\projects\rust\src\libcore\macros.rs:26
  10:     0x7ff7cd936e29 - core::result::Result<(), std::sync::mpsc::SendError<multiinput::manager::Command>>::unwrap<(),std::sync::mpsc::SendError<multiinput::manager::Command>>
                               at C:\projects\rust\src\libcore\result.rs:782
  11:     0x7ff7cd9286d0 - multiinput::manager::{{impl}}::drop
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\src\manager.rs:140
  12:     0x7ff7cd9161ae - core::ptr::drop_in_place<multiinput::manager::RawInputManager>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  13:     0x7ff7cd911279 - apitest::main
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\examples\apitest.rs:25
  14:     0x7ffe0406c8bf - _C_specific_handler
  15:     0x7ffe04062be6 - _TypeMatch
  16:     0x7ffe04061ee2 - is_exception_typeof
  17:     0x7ffe0406bfaf - _CxxFrameHandler3
  18:     0x7ffe2484513c - _chkstk
  19:     0x7ffe247be524 - RtlUnwindEx
  20:     0x7ffe0406c358 - FindAndUnlinkFrame
  21:     0x7ffe04062d38 - _TypeMatch
  22:     0x7ffe040623dd - is_exception_typeof
  23:     0x7ffe04061fde - is_exception_typeof
  24:     0x7ffe0406bfaf - _CxxFrameHandler3
  25:     0x7ffe248450bc - _chkstk
  26:     0x7ffe247bd277 - RtlWalkFrameChain
  27:     0x7ffe247bb6e2 - RtlRaiseException
  28:     0x7ffe20d84007 - RaiseException
  29:     0x7ffe040646e1 - CxxThrowException
  30:     0x7ff7cd9b4e6b - panic_unwind::imp::panic
                               at C:\projects\rust\src\libpanic_unwind\seh.rs:291
  31:     0x7ff7cd9b4e6b - panic_unwind::__rust_start_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:118
  32:     0x7ff7cd9a610e - std::panicking::rust_panic
                               at C:\projects\rust\src\libstd\panicking.rs:433
  33:     0x7ff7cd9a60bb - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:418
  34:     0x7ff7cd9a5d9f - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:349
  35:     0x7ff7cd9a5cc1 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:325
  36:     0x7ff7cd9b657c - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:72
  37:     0x7ff7cd9395e5 - core::result::unwrap_failed<std::sync::mpsc::RecvError>
                               at C:\projects\rust\src\libcore\macros.rs:26
  38:     0x7ff7cd937172 - core::result::Result<core::option::Option<multiinput::event::RawEvent>, std::sync::mpsc::RecvError>::unwrap<core::option::Option<multiinput::event::RawEvent>,std::sync::mpsc::RecvError>
                               at C:\projects\rust\src\libcore\result.rs:782
  39:     0x7ff7cd928631 - multiinput::manager::RawInputManager::get_event
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\src\manager.rs:117
  40:     0x7ff7cd9110b4 - apitest::main
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\examples\apitest.rs:11
  41:     0x7ff7cd919d53 - std::rt::lang_start::{{closure}}<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  42:     0x7ff7cd9a5bfc - std::rt::lang_start_internal::{{closure}}
                               at C:\projects\rust\src\libstd\rt.rs:59
  43:     0x7ff7cd9a5bfc - std::panicking::try::do_call<closure,i32>
                               at C:\projects\rust\src\libstd\panicking.rs:306
  44:     0x7ff7cd9b4d91 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  45:     0x7ff7cd9aa202 - std::panicking::try
                               at C:\projects\rust\src\libstd\panicking.rs:285
  46:     0x7ff7cd9aa202 - std::panic::catch_unwind
                               at C:\projects\rust\src\libstd\panic.rs:361
  47:     0x7ff7cd9aa202 - std::rt::lang_start_internal
                               at C:\projects\rust\src\libstd\rt.rs:58
  48:     0x7ff7cd919d23 - std::rt::lang_start<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  49:     0x7ff7cd9112b6 - main
  50:     0x7ff7cd9c13f0 - invoke_main
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  51:     0x7ff7cd9c13f0 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  52:     0x7ffe22551fe3 - BaseThreadInitThunk
  53:     0x7ffe2480f060 - RtlUserThreadStart
thread panicked while panicking. aborting.
error: process didn't exit successfully: `target\debug\examples\apitest.exe` (exit code: 3221225501)
```

**Comment by Jonesey13** [comment]
Would be interesting to know what error code HidP_GetUsageValue returns. If all the axes/buttons are still working on the joystick then maybe this particular input is registered but unused on the device (and we may just have to have to skip over or log it rather than panicking)

**Comment by MrMinimal** [comment]
From the log above you can tell the GetUsageValue values. I have added that part myself, but I cant interpret that value. Probably some bit shifting magic right?
```
HidP_GetUsageValue returns: -1072627702
Should be: 1114112
```

**Comment by Jonesey13** [comment]
Yes that what it looks like. Probably easiest if I pull in the codes from winapi-rs and check if there's a match.

**Comment by MrMinimal** [comment]
https://github.com/retep998/winapi-rs/blob/d8290fc406c8e390101dd225f7ec506848fc86ce/src/shared/hidpi.rs#L375

Well the macro does a bit of bit shifting as far as I can tell:

https://github.com/retep998/winapi-rs/blob/baec1df1b8e8e2232d587318f065fd4cb599cb4f/src/macros.rs#L24

**Comment by Jonesey13** [comment]
Apparently -1072627702 corresponds to HIDP_STATUS_INCOMPATIBLE_REPORT_ID

**Comment by Jonesey13** [comment]
Does your joystick have force feedback by any chance?

**Comment by Jonesey13** [comment]
I reckon it's a cap that's outside the HID's reported usage page and should probably just be ignored for the purposes of this library.

**Comment by Jonesey13** [comment]
Pushed a new version to cargo. Let me know if this fixes the error for you!

**Comment by MrMinimal** [comment]
Works like a charm! Thank you so much for the quick fix
