### ISSUE TITLE
Panic when joystick has no buttons

### ISSUE THREAD

**Issue by MrMinimal** [Jonesey13/multiinput-rust#4]
When using my Saitek Cessna Rudder Pedals the project panics at
https://github.com/Jonesey13/multiinput-rust/blob/master/src/rawinput.rs#L274

Thrustmaster Warthog Joystick and Throtte work both fine. I suspect it happens because the pedals have no buttons, only axis.

with the following log:
```
PS C:\Users\Dev\Documents\RustProjects\multiinput-rust> cargo run --example apitest
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\examples\apitest.exe`
thread '<unnamed>' panicked at 'assertion failed: HidP_GetButtonCaps(HidP_Input,
                   p_button_caps.as_mut_ptr() as PHIDP_BUTTON_CAPS,
                   &mut caps_length,
                   preparsed_data.as_mut_ptr() as PHIDP_PREPARSED_DATA) ==
    HIDP_STATUS_SUCCESS', src\rawinput.rs:274:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', libcore\result.rs:945:5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', libcore\result.rs:945:5
stack backtrace:
   0:     0x7ff7abafa29a - std::sys::windows::backtrace::unwind_backtrace
                               at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1:     0x7ff7abb00aff - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2:     0x7ff7abb00aff - std::sys_common::backtrace::print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff7abaf572e - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:207
   4:     0x7ff7abaf53da - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:223
   5:     0x7ff7abaf5cee - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:402
   6:     0x7ff7abaf5a9f - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:349
   7:     0x7ff7abaf59c1 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:325
   8:     0x7ff7abb0627c - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:72
   9:     0x7ff7aba894c2 - core::result::unwrap_failed<std::sync::mpsc::SendError<multiinput::manager::Command>>
                               at C:\projects\rust\src\libcore\macros.rs:26
  10:     0x7ff7aba86e29 - core::result::Result<(), std::sync::mpsc::SendError<multiinput::manager::Command>>::unwrap<(),std::sync::mpsc::SendError<multiinput::manager::Command>>
                               at C:\projects\rust\src\libcore\result.rs:782
  11:     0x7ff7aba786d0 - multiinput::manager::{{impl}}::drop
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\src\manager.rs:140
  12:     0x7ff7aba661ae - core::ptr::drop_in_place<multiinput::manager::RawInputManager>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  13:     0x7ff7aba61279 - apitest::main
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\examples\apitest.rs:25
  14:     0x7ffe0406c8bf - _C_specific_handler
  15:     0x7ffe04062be6 - _TypeMatch
  16:     0x7ffe04061ee2 - is_exception_typeof
  17:     0x7ffe0406bfaf - _CxxFrameHandler3
  18:     0x7ffe2484513c - _chkstk
  19:     0x7ffe247be524 - RtlUnwindEx
  20:     0x7ffe0406c358 - FindAndUnlinkFrame
  21:     0x7ffe04062d38 - _TypeMatch
  22:     0x7ffe040623dd - is_exception_typeof
  23:     0x7ffe04061fde - is_exception_typeof
  24:     0x7ffe0406bfaf - _CxxFrameHandler3
  25:     0x7ffe248450bc - _chkstk
  26:     0x7ffe247bd277 - RtlWalkFrameChain
  27:     0x7ffe247bb6e2 - RtlRaiseException
  28:     0x7ffe20d84007 - RaiseException
  29:     0x7ffe040646e1 - CxxThrowException
  30:     0x7ff7abb04b6b - panic_unwind::imp::panic
                               at C:\projects\rust\src\libpanic_unwind\seh.rs:291
  31:     0x7ff7abb04b6b - panic_unwind::__rust_start_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:118
  32:     0x7ff7abaf5e0e - std::panicking::rust_panic
                               at C:\projects\rust\src\libstd\panicking.rs:433
  33:     0x7ff7abaf5dbb - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:418
  34:     0x7ff7abaf5a9f - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:349
  35:     0x7ff7abaf59c1 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:325
  36:     0x7ff7abb0627c - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:72
  37:     0x7ff7aba895e5 - core::result::unwrap_failed<std::sync::mpsc::RecvError>
                               at C:\projects\rust\src\libcore\macros.rs:26
  38:     0x7ff7aba87172 - core::result::Result<core::option::Option<multiinput::event::RawEvent>, std::sync::mpsc::RecvError>::unwrap<core::option::Option<multiinput::event::RawEvent>,std::sync::mpsc::RecvError>
                               at C:\projects\rust\src\libcore\result.rs:782
  39:     0x7ff7aba785bf - multiinput::manager::RawInputManager::register_devices
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\src\manager.rs:111
  40:     0x7ff7aba61063 - apitest::main
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\examples\apitest.rs:6
  41:     0x7ff7aba69d53 - std::rt::lang_start::{{closure}}<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  42:     0x7ff7abaf58fc - std::rt::lang_start_internal::{{closure}}
                               at C:\projects\rust\src\libstd\rt.rs:59
  43:     0x7ff7abaf58fc - std::panicking::try::do_call<closure,i32>
                               at C:\projects\rust\src\libstd\panicking.rs:306
  44:     0x7ff7abb04a91 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  45:     0x7ff7abaf9f02 - std::panicking::try
                               at C:\projects\rust\src\libstd\panicking.rs:285
  46:     0x7ff7abaf9f02 - std::panic::catch_unwind
                               at C:\projects\rust\src\libstd\panic.rs:361
  47:     0x7ff7abaf9f02 - std::rt::lang_start_internal
                               at C:\projects\rust\src\libstd\rt.rs:58
  48:     0x7ff7aba69d23 - std::rt::lang_start<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  49:     0x7ff7aba612b6 - main
  50:     0x7ff7abb110f0 - invoke_main
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  51:     0x7ff7abb110f0 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  52:     0x7ffe22551fe3 - BaseThreadInitThunk
  53:     0x7ffe2480f060 - RtlUserThreadStart
thread panicked while panicking. aborting.
error: process didn't exit successfully: `target\debug\examples\apitest.exe` (exit code: 3221225501)
```

**Comment by Jonesey13** [comment]
Yes this can hopefully be fixed by skipping this logic whenever caps_length == 0 (cheers for the suggestion!)

**Comment by Jonesey13** [comment]
Pushed a new version to cargo. Let me know if this fixes the error for you!

**Comment by MrMinimal** [comment]
Wicked! I'm testing it right away. Brb.

**Comment by MrMinimal** [comment]
Just tested it. Not sure if this error is related, but it only happens on the latest `master` with the rudder pedals (which don't have buttons) when I move any axis.

![image](https://user-images.githubusercontent.com/8739690/40020177-b2059ab4-57c1-11e8-9aa1-bbe019748de8.png)


```
$ RUST_BACKTRACE=1 cargo run --example apitest
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target\debug\examples\apitest.exe`
Mice:
["\\\\?\\HID#VID_093A&PID_2521#6&2c46c546&0&0000#{378de44c-56ef-11d1-bc8c-00a0c91405dd}\u{0}"]
None
["\\\\?\\HID#VID_04D9&PID_0141&MI_02&Col03#7&2b29a21e&0&0002#{378de44c-56ef-11d1-bc8c-00a0c91405dd}\u{0}"]
None
Keyboards:
["\\\\?\\HID#VID_04D9&PID_0141&MI_02&Col04#7&2b29a21e&0&0003#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}\u{0}"]
None
["\\\\?\\HID#VID_04D9&PID_0141&MI_00#7&15f24e50&0&0000#{884b96c3-56ef-11d1-bc8c-00a0c91405dd}\u{0}"]
None
Hids:
["\\\\?\\HID#VID_06A3&PID_0765#6&54e22ef&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\u{0}"]
None
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', C:\projects\rust\src\libcore\slice\mod.rs:865:10
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:207
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:223
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:402
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:349
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:72
   9: core::panicking::panic_bounds_check
             at C:\projects\rust\src\libcore\panicking.rs:58
  10: core::slice::{{impl}}::index<winapi::shared::hidpi::HIDP_BUTTON_CAPS>
             at C:\projects\rust\src\libcore\slice\mod.rs:865
  11: core::slice::{{impl}}::index<winapi::shared::hidpi::HIDP_BUTTON_CAPS,usize>
             at C:\projects\rust\src\libcore\slice\mod.rs:767
  12: alloc::vec::{{impl}}::index<winapi::shared::hidpi::HIDP_BUTTON_CAPS,usize>
             at C:\projects\rust\src\liballoc\vec.rs:1648
  13: multiinput::joystick::process_joystick_data
             at .\src\joystick.rs:20
  14: multiinput::rawinput::read_input_buffer
             at .\src\rawinput.rs:78
  15: multiinput::rawinput::get_event
             at .\src\rawinput.rs:90
  16: multiinput::manager::{{impl}}::new::{{closure}}
             at .\src\manager.rs:88
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:207
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:223
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:402
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:349
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:72
   9: core::result::unwrap_failed<std::sync::mpsc::RecvError>
             at C:\projects\rust\src\libcore\macros.rs:26
  10: core::result::Result<core::option::Option<multiinput::event::RawEvent>, std::sync::mpsc::RecvError>::unwrap<core::option::Option<multiinput::event::RawEvent>,std::sync::mpsc::RecvError>
             at C:\projects\rust\src\libcore\result.rs:782
  11: multiinput::manager::RawInputManager::get_event
             at .\src\manager.rs:117
  12: apitest::main
             at .\examples\apitest.rs:11
  13: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  14: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  15: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:306
  16: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  17: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:285
  18: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:361
  19: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  20: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  21: main
  22: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  23: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  24: BaseThreadInitThunk
  25: RtlUserThreadStart
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', libcore\result.rs:945:5
stack backtrace:
   0:     0x7ff7ad87a30a - std::sys::windows::backtrace::unwind_backtrace
                               at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1:     0x7ff7ad880b6f - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2:     0x7ff7ad880b6f - std::sys_common::backtrace::print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff7ad87579e - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:207
   4:     0x7ff7ad87544a - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:223
   5:     0x7ff7ad875d5e - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:402
   6:     0x7ff7ad875b0f - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:349
   7:     0x7ff7ad875a31 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:325
   8:     0x7ff7ad8862ec - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:72
   9:     0x7ff7ad808ec2 - core::result::unwrap_failed<std::sync::mpsc::SendError<multiinput::manager::Command>>
                               at C:\projects\rust\src\libcore\macros.rs:26
  10:     0x7ff7ad806ad9 - core::result::Result<(), std::sync::mpsc::SendError<multiinput::manager::Command>>::unwrap<(),std::sync::mpsc::SendError<multiinput::manager::Command>>
                               at C:\projects\rust\src\libcore\result.rs:782
  11:     0x7ff7ad7f86d0 - multiinput::manager::{{impl}}::drop
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\src\manager.rs:140
  12:     0x7ff7ad7e644e - core::ptr::drop_in_place<multiinput::manager::RawInputManager>
                               at C:\projects\rust\src\libcore\ptr.rs:59
  13:     0x7ff7ad7e1279 - apitest::main
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\examples\apitest.rs:25
  14:     0x7ffa9335c8bf - _C_specific_handler
  15:     0x7ffa93352be6 - _TypeMatch
  16:     0x7ffa93351ee2 - is_exception_typeof
  17:     0x7ffa9335bfaf - _CxxFrameHandler3
  18:     0x7ffaa552513c - _chkstk
  19:     0x7ffaa549e524 - RtlUnwindEx
  20:     0x7ffa9335c358 - FindAndUnlinkFrame
  21:     0x7ffa93352d38 - _TypeMatch
  22:     0x7ffa933523dd - is_exception_typeof
  23:     0x7ffa93351fde - is_exception_typeof
  24:     0x7ffa9335bfaf - _CxxFrameHandler3
  25:     0x7ffaa55250bc - _chkstk
  26:     0x7ffaa549d277 - RtlWalkFrameChain
  27:     0x7ffaa549b6e2 - RtlRaiseException
  28:     0x7ffaa1bb4007 - RaiseException
  29:     0x7ffa933546e1 - CxxThrowException
  30:     0x7ff7ad884bdb - panic_unwind::imp::panic
                               at C:\projects\rust\src\libpanic_unwind\seh.rs:291
  31:     0x7ff7ad884bdb - panic_unwind::__rust_start_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:118
  32:     0x7ff7ad875e7e - std::panicking::rust_panic
                               at C:\projects\rust\src\libstd\panicking.rs:433
  33:     0x7ff7ad875e2b - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:418
  34:     0x7ff7ad875b0f - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:349
  35:     0x7ff7ad875a31 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:325
  36:     0x7ff7ad8862ec - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:72
  37:     0x7ff7ad809125 - core::result::unwrap_failed<std::sync::mpsc::RecvError>
                               at C:\projects\rust\src\libcore\macros.rs:26
  38:     0x7ff7ad8068c2 - core::result::Result<core::option::Option<multiinput::event::RawEvent>, std::sync::mpsc::RecvError>::unwrap<core::option::Option<multiinput::event::RawEvent>,std::sync::mpsc::RecvError>
                               at C:\projects\rust\src\libcore\result.rs:782
  39:     0x7ff7ad7f8631 - multiinput::manager::RawInputManager::get_event
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\src\manager.rs:117
  40:     0x7ff7ad7e10b4 - apitest::main
                               at C:\Users\Dev\Documents\RustProjects\multiinput-rust\examples\apitest.rs:11
  41:     0x7ff7ad7e9d53 - std::rt::lang_start::{{closure}}<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  42:     0x7ff7ad87596c - std::rt::lang_start_internal::{{closure}}
                               at C:\projects\rust\src\libstd\rt.rs:59
  43:     0x7ff7ad87596c - std::panicking::try::do_call<closure,i32>
                               at C:\projects\rust\src\libstd\panicking.rs:306
  44:     0x7ff7ad884b01 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:102
  45:     0x7ff7ad879f72 - std::panicking::try
                               at C:\projects\rust\src\libstd\panicking.rs:285
  46:     0x7ff7ad879f72 - std::panic::catch_unwind
                               at C:\projects\rust\src\libstd\panic.rs:361
  47:     0x7ff7ad879f72 - std::rt::lang_start_internal
                               at C:\projects\rust\src\libstd\rt.rs:58
  48:     0x7ff7ad7e9d23 - std::rt::lang_start<()>
                               at C:\projects\rust\src\libstd\rt.rs:74
  49:     0x7ff7ad7e12b6 - main
  50:     0x7ff7ad891160 - invoke_main
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  51:     0x7ff7ad891160 - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  52:     0x7ffaa5101fe3 - BaseThreadInitThunk
  53:     0x7ffaa54ef060 - RtlUserThreadStart
thread panicked while panicking. aborting.
error: process didn't exit successfully: `target\debug\examples\apitest.exe` (exit code: 3221225501)
Illegal instruction

```

**Comment by Jonesey13** [comment]
Ah that's somewhere else that assumes buttons exist! Looks easy to fix...

**Comment by Jonesey13** [comment]
OK I've pushed another fix (let's hope there's not something else I've missed!)

**Comment by MrMinimal** [comment]
Yeah that one did it! Thank you so much for the quick fixed, this project needs way more exposure!
